### ISSUE TITLE
unprivileged pflask cannot mount cgroup2

### ISSUE THREAD

**Issue by ghost** [ghedo/pflask#19]
> $ pflask -r container/  --user-map=0:1672864:65536 -u root -t container01 --netif -- /bin/bash
> [✘] Error mounting 'cgroup2': Operation not permitted
> [✘] Child failed with code '1'

It's probably quite similar to the situation with NETNS:
https://github.com/ghedo/pflask/issues/4#issuecomment-145606341

and solvable with CLONE_NEWCGROUP
https://github.com/culugyx/pflask/commit/5ef9b0ac60f77ec7edf4497f74ade517287868bb

> $ pflask -r container/  --user-map=0:1672864:65536 -u root -t container01 --netif -- /bin/bash
> root@container01:/#

Perhaps it's better to add a separate command line option to control this, if there's any drawbacks of a new cgroup namespace.

**Comment by ghedo** [comment]
Could you please open a PR with your patch? I'll try to find some time to test it.

**Comment by ghost** [comment]
Sure, PR at https://github.com/ghedo/pflask/pull/20

**Comment by ghedo** [comment]
I merged your PR now. However unprivileged `pflask` with `--chroot` still fails for me because now it fails to mount `/sys`, sigh:
```
 % build/pflask --user-map=0:100000:65536 --chroot=$HOME/local/rootfs
[✘] Error mounting 'sysfs': Operation not permitted
[✘] Child failed with code '1'
```
AFAICT e.g. [runc deals with this](https://github.com/opencontainers/runc/blob/13fa5d2953d2fabbf14c2f6fd05eac70d71c45c7/libcontainer/specconv/example.go#L209) by mounting `/sys` as a recursive bind mount instead of a proper `sysfs` mount. However that means that we inherit all the cgroup mounts from the host system as well, which totally defeats the purpose of mounting `cgroup2` in the first place...

**Comment by ghedo** [comment]
Made https://github.com/ghedo/pflask/tree/sys_bind to test mounting `/sys` as bind mount.

**Comment by ghost** [comment]
Hi,

This failure don't seem to be introduced by the recent patches: (this is on master: 6b915b2)
> $ pflask -r $PWD/container --user-map=0:1672864:65536
> [✘] Error mounting 'sysfs': Operation not permitted
> [✘] Child failed with code '1'
> $ pflask -r $PWD/container --user-map=0:1672864:65536 --netif
> -bash-4.4# 

I think they were discussed in https://github.com/ghedo/pflask/issues/4,
and for unprivileged containers, "--netif" is probably required.

**Comment by ghedo** [comment]
Yeah, didn't mean your patch broke it. In any case you are right, I totally forgot about that discussion :/

Anyway, closing this now since the patch was merged.

**Comment by ghost** [comment]
No problem. :)
